# Generated by Django 4.0 on 2021-12-08 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_menumodel_menuitemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItemModel',
        ),
        migrations.DeleteModel(
            name='MenuModel',
        ),
    ]
