# Generated by Django 4.0 on 2021-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labordeliverytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverytypename', models.CharField(blank=True, db_column='DeliveryTypeName', max_length=150, null=True)),
                ('deliveryusedescription', models.CharField(blank=True, db_column='DeliveryUseDescription', max_length=150, null=True)),
                ('memodeliverynote1', models.CharField(blank=True, db_column='MemoDeliveryNote1', max_length=150, null=True)),
                ('deliveryownerfirstname', models.CharField(blank=True, db_column='DeliveryOwnerFirstName', max_length=150, null=True)),
                ('deliveryownerlastname', models.CharField(blank=True, db_column='DeliveryOwnerLastName', max_length=150, null=True)),
                ('deliveryownerfullname', models.CharField(blank=True, db_column='DeliveryOwnerFullName', max_length=150, null=True)),
                ('deliveryowneremail', models.CharField(blank=True, db_column='DeliveryOwnerEmail', max_length=150, null=True)),
                ('createby', models.CharField(blank=True, db_column='CreateBy', max_length=150, null=True)),
            ],
        ),
    ]
