# Generated by Django 4.0 on 2021-12-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statusstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusstatename', models.CharField(blank=True, db_column='StatusStateName', max_length=150, null=True)),
                ('statusstatedesc', models.CharField(blank=True, db_column='StatusStateDesc', max_length=150, null=True)),
                ('statusstatetype', models.CharField(blank=True, db_column='StatusStateType', max_length=150, null=True)),
                ('memo', models.CharField(blank=True, db_column='Memo', max_length=150, null=True)),
            ],
        ),
    ]
